apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cert-monitor
  name: cert-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-monitor
  strategy: {}
  template:
    metadata:
      labels:
        app: cert-monitor
    spec:
      containers:
      - image: herubuilds.azurecr.io/kube-cert-monitor
        name: cert-monitor
        resources: 
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "64Mi"
            cpu: "125m"
        ports:
        - containerPort: 9100
      serviceAccountName: cert-monitor-user
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-monitor-user